spring:
  application:
    name: resource-server

server:
  port: 8080

application:
  security:
    issuer: http://localhost:9000
    jwk-set-uri: http://localhost:9000/oauth2/jwks
    audience: mini-resource-server
    token-type: oauth-mini+jwt
    jwks-connect-timeout: 2s
    jwks-read-timeout: 2s
