spring:
  application:
    name: authorization-server
  mvc:
    problemdetails:
      enabled: true

server:
  port: 9000
  tomcat:
    max-http-form-post-size: 16KB

application:
  security:
    issuer: http://localhost:9000
    audience: mini-resource-server
    token-type: oauth-mini+jwt
    access-token-ttl: 5m
